### PR TITLE
Get tests running in Eclipse and fix Travis

### PR DESCRIPTION
**Pull request by massdosage**
- upgrade junit to 5.6.0 (and import bom)
- upgrade mockito to 3.2.4
- removed override of surefire

### CODE REVIEW

**Comment by massdosage** [comment]
I've purposefully not updated the CHANGELOG since these are internal-only changes.

**Comment by massdosage** [comment]
Looks like we need to enable surefire specifically, will do this in eg-oss-parent and upgrade that and then depend on the new version from here.

**Comment by massdosage** [comment]
OK, tests run fine for me via Maven CLI locally and in Eclipse. We're getting timeouts running the integration in Travis but this could be due to general Travis scaling issues which we've seen before. @max-jacobs would you mind trying this branch out locally and just checking it works like you would expect?

**Comment by KenFigueiredo** [comment]
Hey @massdosage!

I opened up https://github.com/ExpediaGroup/beekeeper/pull/39 against this branch to see if the issues went away in GH Actions, which they seem to do. I've set that pipeline up so if we want to try rolling either both Travis & GH Actions on this repository or swap out to just GH actions to have more consistent builds 

Let me know if you have any additional thoughts / concerns about that approach 😄

**Comment by massdosage** [comment]
> Hey @massdosage!
> 
> I opened up #39 against this branch to see if the issues went away in GH Actions, which they seem to do. I've set that pipeline up so if we want to try rolling either both Travis & GH Actions on this repository or swap out to just GH actions to have more consistent builds
> 
> Let me know if you have any additional thoughts / concerns about that approach smile

Excellent, I'll take a look at that when I get a chance. For now let's go with GH Actions *and* Travis and we can compare them over the next few weeks. If GH actions proves to be more stable (which is what I suspect will be the case) then we can remove Travis.

**Pull request merged**
